# Node.js
# Build a general Node.js application with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/javascript

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: NodeTool@8
    inputs:
      versionSpec: '8.x'
    displayName: 'Install Node.js'
  - script: |
      npm install
      npm run ci
    displayName: 'npm install and build'
- job: macOS
  pool:
    vmImage: 'xcode9-macos10.13'
  steps:
  - task: NodeTool@8
    inputs:
      versionSpec: '8.x'
    displayName: 'Install Node.js'
  - script: |
      npm install
      npm run ci
    displayName: 'npm install and build'
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: NodeTool@8
    inputs:
      versionSpec: '8.x'
    displayName: 'Install Node.js'
  - script: |
      npm install
      npm run ci
    displayName: 'npm install and build'